id: QmbLuW4P7xrfmn6118Wv6NQiSaPRoCWRrDmv9r4KdFRARX
description: ""
tags: []
source: libraries/pixel_collab_backend
trigger:
    type: https
    method: GET
    paths:
        - /api/clearChat
domains:
    - main
execution:
    timeout: 10s
    memory: 10MB
    call: clearChat
