id: QmYK4bjNYR3LNfTQWsUGbfYdfEQNerZofZ2QK4CjdyEkJc
description: ""
tags: []
source: libraries/pixel_collab_backend
trigger:
    type: https
    method: GET
    paths:
        - /api/clearData
domains:
    - main
execution:
    timeout: 10s
    memory: 10MB
    call: clearData
