id: QmcsEdWTAGa5BDNEM2XDgpUrWQsjqVdS9xrNb4ekbiR2Kp
description: ""
tags: []
source: libraries/pixel_collab_backend
trigger:
    type: https
    method: GET
    paths:
        - /api/clearCanvas
domains:
    - main
execution:
    timeout: 10s
    memory: 10MB
    call: clearCanvas
