id: QmRFYXB9ibhgWZihk88ccNzRLfmYG78cNFQvjyC4agRJgo
description: ""
tags: []
source: libraries/pixel_collab_backend
trigger:
    type: https
    method: GET
    paths:
        - /api/getMessages
domains:
    - main
execution:
    timeout: 10s
    memory: 10MB
    call: getMessages
