id: Qmc8zDi8C2QrvQdjLBfKNPvQoKVHPhGp5bPfE4xbCRHoyE
description: ""
tags: []
source: libraries/pixel_collab_backend
trigger:
    type: https
    method: POST
    paths:
        - /api/initCanvas
domains:
    - main
execution:
    timeout: 10s
    memory: 10MB
    call: initCanvas
