id: QmSKLzUqmBbZT3S3poWeUoVCaCCEgKW1mrekfGkQcJba9H
description: ""
tags: []
source: libraries/pixel_collab_backend
trigger:
    type: https
    method: POST
    paths:
        - /api/joinGame
domains:
    - GeneratedDomain
execution:
    timeout: 10s
    memory: 10MB
    call: joinGame
