id: QmbA9Ya7oPx2yjBNq9uL393enr9vEyWyWJd9538jzGRDSK
description: ""
tags: []
source: libraries/pixel_collab_backend
trigger:
    type: pub-sub
    channel: pixelupdates
execution:
    timeout: 10s
    memory: 10MB
    call: onPixelUpdate
