id: QmVbBrrGVCZw6JDhayvnjq8G1oJV2hHbxaAc2ZaxvpDUqx
description: ""
tags: []
source: libraries/pixel_collab_backend
trigger:
    type: https
    method: POST
    paths:
        - /api/placePixel
domains:
    - main
execution:
    timeout: 10s
    memory: 10MB
    call: placePixel
