id: QmZdD98phArkAkzWNoiD5XccaAMmgmtfeP5g8ebgFBgKcQ
description: ""
tags: []
source: libraries/pixel_collab_backend
trigger:
    type: https
    method: POST
    paths:
        - /api/sendMessage
domains:
    - GeneratedDomain
execution:
    timeout: 10s
    memory: 10MB
    call: sendMessage
